[LegalNotice]
Accepted=true

[Preferences]
Connection\PortRangeMin=6881
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
Downloads\TempPathEnabled=true
Queueing\QueueingEnabled=true
WebUI\Address=*
WebUI\AuthSubnetWhitelist=172.16.0.0/12
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\CSRFProtection=false
WebUI\HostHeaderValidation=false
WebUI\LocalHostAuth=false
WebUI\Port=8080
